language: ruby
rvm: 2.2.2
cache: bundler
sudo: false

install:
 - bundle config build.nokogiri --use-system-libraries
 - travis_retry bundle install

script:
 - bundle exec jekyll build
 - bundle exec mdl -s markdownlint-config.rb . || true  # markdownlint errors shouldn't fail the build for now
 - bundle exec htmlproofer ./_site --disable-external --allow-hash-href --check-html

branches:
  only:
    - gh-pages
