baseurl: http://akoeplinger.github.com/mono-project.com
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
paginate: 5
paginate_path: "news/page/:num"

safe: true
exclude:
  - CNAME
  - README.md
  - Gemfile*
