relative_permalinks: false
permalink: pretty
paginate: 5
paginate_path: "news/page/:num"
highlighter: null   # we use a javascript based highlighter
markdown: kramdown
kramdown:
  input: GFM

#safe: true  # needs Jekyll 2.0
gems:
  - jekyll-redirect-from
exclude:
  - CNAME
  - README.md
  - CONTRIBUTING.md
  - Gemfile*
