baseurl: /mono-project.com
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
paginate: 5
paginate_path: "news/page/:num"
markdown: kramdown


lsi: false
pygments: true
gems:
  - jekyll-redirect-from
exclude:
  - CNAME
  - README.md
  - Gemfile*
